[package]
name = "my_cart_ganu_doomer"
version = "0.1.0"
edition = "2021"
authors = ["doomer"]
description = "A demo app used for something "
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
